CREATE TABLE IF NOT EXISTS "Author" (
    "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "Genre" (
    "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL  
);

CREATE TABLE IF NOT EXISTS "Book" (
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title"     TEXT NOT NULL,
    "author_id" INTEGER NOT NULL,
    FOREIGN KEY ("author_id") REFERENCES "Author"("id") ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS "BookGenre" (
    "book_id"  INTEGER NOT NULL,
    "genre_id" INTEGER NOT NULL,
    PRIMARY KEY ("book_id", "genre_id"),
    FOREIGN KEY ("book_id")  REFERENCES "Book"("id")  ON DELETE CASCADE,
    FOREIGN KEY ("genre_id") REFERENCES "Genre"("id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Branch" (
    "id"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "address" TEXT NOT NULL,
    "phone"   TEXT NOT NULL  
);


CREATE TABLE IF NOT EXISTS "Language" (
    "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS "shelf" (
    "id"         SERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "floor"      INTEGER NOT NULL,
    "branch_id"  INTEGER NOT NULL,
    FOREIGN KEY ("branch_id") REFERENCES "Branch"("id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Copy" (
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "book_id"     INTEGER NOT NULL,
    "branch_id"   INTEGER NOT NULL,
    "shelf_id"    INTEGER NOT NULL,
    "language_id" INTEGER, 
    "status"      TEXT NOT NULL,
    FOREIGN KEY ("book_id")     REFERENCES "Book"("id")     ON DELETE RESTRICT,
    FOREIGN KEY ("branch_id")   REFERENCES "Branch"("id")   ON DELETE RESTRICT,
    FOREIGN KEY ("shelf_id")    REFERENCES "shelf"("id")    ON DELETE RESTRICT,
    FOREIGN KEY ("language_id") REFERENCES "Language"("id") ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS "Member" (
    "id"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"  TEXT,
    "phone" TEXT,
    "email" TEXT
);


CREATE TABLE IF NOT EXISTS "MemberProfile" (
    "member_id"  INTEGER PRIMARY KEY,
    "birth_date" DATE,       
    "address"    TEXT NOT NULL,
    FOREIGN KEY ("member_id") REFERENCES "Member"("id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "Loan" (
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "copy_id"     INTEGER NOT NULL,
    "member_id"   INTEGER NOT NULL,
    "loan_date"   DATE NOT NULL,
    "return_date" DATE NOT NULL,
    FOREIGN KEY ("copy_id")   REFERENCES "Copy"("id")   ON DELETE RESTRICT,
    FOREIGN KEY ("member_id") REFERENCES "Member"("id") ON DELETE RESTRICT
);